apiVersion: fence-agents-remediation.medik8s.io/v1alpha1
kind: FenceAgentsRemediation
metadata:
  name: far-node-remediation
  namespace: openshift-workload-availability
spec:
  # Fence agent type (fence_ipmilan for IPMI-based fencing)
  agent: fence_ipmilan

  # Number of retry attempts
  retrycount: 3

  # Interval between retries
  retryinterval: "5s"

  # Timeout for fence operation
  timeout: "60s"

  # Shared parameters for all nodes
  sharedparameters:
    # IPMI username (update with your credentials)
    --username: "ADMIN"
    # IPMI password (update with your credentials)
    # NOTE: In production, use a Secret instead of plaintext
    --password: "YOUR_IPMI_PASSWORD"
    # Use IPMI LAN Plus protocol
    --lanplus: ""
    # Action to perform (reboot, off, on)
    --action: reboot

  # Node-specific parameters
  nodeparameters:
    # BMC IP address for each node
    --ip:
      # Update with your node name and BMC address
      worker-node-1: bmc.worker-node-1.example.com
    # BMC port (usually 623 for IPMI)
    --ipport:
      worker-node-1: "623"

---
# Example for multiple nodes
# apiVersion: fence-agents-remediation.medik8s.io/v1alpha1
# kind: FenceAgentsRemediation
# metadata:
#   name: far-multi-node-remediation
#   namespace: openshift-workload-availability
# spec:
#   agent: fence_ipmilan
#   retrycount: 3
#   retryinterval: "5s"
#   timeout: "60s"
#   sharedparameters:
#     --username: "ADMIN"
#     --password: "YOUR_IPMI_PASSWORD"
#     --lanplus: ""
#     --action: reboot
#   nodeparameters:
#     --ip:
#       worker-node-1: bmc.worker-node-1.example.com
#       worker-node-2: bmc.worker-node-2.example.com
#       worker-node-3: bmc.worker-node-3.example.com
#     --ipport:
#       worker-node-1: "623"
#       worker-node-2: "623"
#       worker-node-3: "623"
